### ISSUE TITLE
1.20.1 error on waypoint creation through the GUI

### ISSUE THREAD

**Issue by Sid12323** [Sytm/waypoints2#100]
**Describe the bug**
When attempting to click on any item in the GUI (except for the enchanted books),
`
[21:10:55 ERROR]: Could not pass event InventoryClickEvent to Waypoints v3.6.5
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "name" is null
        at net.minecraft.world.inventory.AnvilMenu.createResult(AnvilMenu.java:309) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.version.Wrapper1_20_R1$AnvilContainer.m(Wrapper1_20_R1.java:96) ~[waypoints-3.6.5.jar:?]
        at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:112) ~[?:?]
        at net.minecraft.world.inventory.ItemCombinerMenu$3.setChanged(ItemCombinerMenu.java:103) ~[?:?]
        at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:207) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftResultInventory.setItem(CraftResultInventory.java:37) ~[purpur-1.20.jar:git-Purpur-1990]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:170) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:37) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:561) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.gui.WaypointsGUI.openCreateWaypoint(WaypointsGUI.kt:159) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.gui.WaypointsGUI.openCreateWaypoint$default(WaypointsGUI.kt:102) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.gui.pages.GUIFolderPage.updateControls$lambda$20(GUIFolderPage.kt:223) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.kinvs.items.GUIItem.click(GUIItem.kt:28) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.kinvs.GUI.onClick$kinvs(GUI.kt:61) ~[waypoints-3.6.5.jar:?]
        at de.md5lukas.waypoints.kinvs.GUIManager.onInventoryClick(GUIManager.kt:82) ~[waypoints-3.6.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:git-Purpur-1990]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.jar:git-Purpur-1990]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.jar:git-Purpur-1990]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3289) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1413) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1990]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`
occurs.

**Additional context**
Running git-Purpur-1990 (MC: 1.20)* & Waypoints 3.6.5

- [x] I am using the latest version of Waypoints available

**Comment by Sytm** [comment]
I am not able to reproduce the issue you are encountering. Also your server is running Minecraft 1.20, not 1.20.1.

After some digging, this looks like to be an Purpur specific bug: https://github.com/PurpurMC/Purpur/blob/2e5dcc63d331fe121d18f37dcecc34be17bf7abb/patches/server/0083-Allow-anvil-colors.patch

**Comment by Sytm** [comment]
This actually seems to be fixed since Purpur 1993. If not please reopen or add another comment
