### ISSUE TITLE
When I track a player, how do I un-track that player without permission?

### ISSUE THREAD

**Issue by paqi-cry** [Sytm/waypoints2#101]
[18:23:49 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalArgumentException: The key inventory.overview.deselect.name.playerTracking is not present in the translation file for the language zh-simplified
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.lang.TranslationLoader.get(TranslationLoader.kt:125)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.lang.Translation.getRawText(Translation.kt:23)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.lang.Translation.withReplacements(Translation.kt:38)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.util.PointerHelperKt.formatCurrentTargets(PointerHelper.kt:34)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.gui.pages.GUIFolderPage.updateControls(GUIFolderPage.kt:239)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.gui.pages.GUIFolderPage.init(GUIFolderPage.kt:441)
[18:23:49 WARN]:        at waypoints-4.0.1(1).jar//de.md5lukas.waypoints.gui.pages.GUIFolderPage$init$1.invokeSuspend(GUIFolderPage.kt)
[18:23:49 WARN]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:23:49 WARN]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[18:23:49 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[18:23:49 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[18:23:49 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[18:23:49 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[18:23:49 WARN]:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [de.md5lukas.waypoints.libs.skedule.BukkitContext@542243fb, StandaloneCoroutine{Cancelling}@1120c71b, BukkitDispatcher@217d6dc5]

**Comment by Sytm** [comment]
Use the updated version [from here](https://modrinth.com/plugin/waypoints/version/4.0.2)
