### ISSUE TITLE
Crashing on plugin enabling.

### ISSUE THREAD

**Issue by Paisley4** [Sytm/waypoints2#109]
**Describe the bug**
Plugin crashes.

**To Reproduce**
Run paper-1.20.6-95 with CommandAPI 9.4.1.

**Expected behavior**
Enable and work.

**Additional context**
[15:47:14 ERROR]: Error occurred while enabling Waypoints v4.5.1 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.commands.Commands vanillaCommandDispatcher'
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.nms.NMS_Common.getBrigadierDispatcher(NMS_Common.java:353) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.CommandAPIBukkit.registerCommandNode(CommandAPIBukkit.java:635) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:647) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.AbstractCommandAPICommand.register(AbstractCommandAPICommand.java:307) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:60) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.Execution.register(Execution.java:38) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.AbstractCommandTree.register(AbstractCommandTree.java:66) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.CommandTree.register(CommandTree.java:32) ~[CommandAPI-9.4.1.jar:?]
        at CommandAPI-9.4.1.jar/dev.jorel.commandapi.ExecutableCommand.register(ExecutableCommand.java:236) ~[CommandAPI-9.4.1.jar:?]
        at waypoints-4.5.1.jar/de.md5lukas.waypoints.command.WaypointsCommand.register(WaypointsCommand.kt:255) ~[waypoints-4.5.1.jar:?]
        at waypoints-4.5.1.jar/de.md5lukas.waypoints.WaypointsPlugin.registerCommands(WaypointsPlugin.kt:226) ~[waypoints-4.5.1.jar:?]
        at waypoints-4.5.1.jar/de.md5lukas.waypoints.WaypointsPlugin.onEnable(WaypointsPlugin.kt:120) ~[waypoints-4.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:47:14 INFO]: [Waypoints] Disabling Waypoints v4.5.1

- [Yes ] I am using the latest version of Waypoints available

**Comment by Sytm** [comment]
You need to compule the latest CommandAPI version yourself if you want to use 1.20.6.

If you are unable to do that, you unfortunately have to wait for JorelAli/CommandAPI#554

**Comment by Paisley4** [comment]
I understand, thank you for help ;). Unluckily it's a server on Aternos so I can't upload "my" compiled version of CommandAPI.

**Comment by Sytm** [comment]
CommandAPI 9.4.2 has been out for a while now
