### ISSUE TITLE
An error ocurred

### ISSUE THREAD

**Issue by thegamerx1** [Sytm/waypoints2#15]
the /waypoint menu worked before but after moving it to my main pc (from server to pc) it doesnt work anymore
windows 10 1909
papermc 1.15.2
plugin 2.6.2 logs are from 2.6.1 but they are the same i think
```
[21:43:48 INFO]: TheGamerX issued server command: /waypoint
[21:43:48 ERROR]: [Md5Lukas-Commons] Couldn't load player store for player with the uuid 867ae82b-6910-3bdb-949d-91041a5a360f
java.util.concurrent.ExecutionException: java.io.EOFException
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.15.2.jar:git-Paper-126]
        at de.md5lukas.commons.data.PlayerStore.getPlayerStore(PlayerStore.java:77) ~[?:?]
        at de.md5lukas.waypoints.data.WPPlayerData.lambda$getPlayerData$0(WPPlayerData.java:43) ~[?:?]
        at java.util.HashMap.compute(Unknown Source) ~[?:1.8.0_231]
        at de.md5lukas.waypoints.data.WPPlayerData.getPlayerData(WPPlayerData.java:41) ~[?:?]
        at de.md5lukas.waypoints.gui.WaypointProvider.<init>(WaypointProvider.java:187) ~[?:?]
        at de.md5lukas.waypoints.gui.GUIManager.openGUI(GUIManager.java:34) ~[?:?]
        at de.md5lukas.waypoints.command.WaypointsCommand.onCommand(WaypointsCommand.java:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-126]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-126]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-126]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedShort(Unknown Source) ~[?:1.8.0_231]
        at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_231]
        at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_231]
        at de.md5lukas.commons.tags.LocationTag.load(LocationTag.java:38) ~[?:?]
        at de.md5lukas.nbt.Tag.readNamedTag(Tag.java:157) ~[?:?]
        at de.md5lukas.nbt.tags.CompoundTag.load(CompoundTag.java:50) ~[?:?]
        at de.md5lukas.nbt.Tag.readNamedTag(Tag.java:157) ~[?:?]
        at de.md5lukas.nbt.tags.CompoundTag.load(CompoundTag.java:50) ~[?:?]
        at de.md5lukas.nbt.Tag.readNamedTag(Tag.java:157) ~[?:?]
        at de.md5lukas.nbt.tags.CompoundTag.load(CompoundTag.java:50) ~[?:?]
        at de.md5lukas.nbt.Tag.readNamedTag(Tag.java:157) ~[?:?]
        at de.md5lukas.nbt.NbtIo.read(NbtIo.java:85) ~[?:?]
        at de.md5lukas.nbt.NbtIo.readCompressed(NbtIo.java:32) ~[?:?]
        at de.md5lukas.nbt.NbtIo.readCompressed(NbtIo.java:47) ~[?:?]
        at de.md5lukas.commons.data.PlayerStore$1.load(PlayerStore.java:70) ~[?:?]
        at de.md5lukas.commons.data.PlayerStore$1.load(PlayerStore.java:66) ~[?:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.15.2.jar:git-Paper-126]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.15.2.jar:git-Paper-126]
        ... 30 more
[21:43:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'waypoint' in plugin Waypoints v2.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-126]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-126]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-126]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-126]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at de.md5lukas.waypoints.data.WPPlayerData.<init>(WPPlayerData.java:60) ~[?:?]
        at de.md5lukas.waypoints.data.WPPlayerData.lambda$getPlayerData$0(WPPlayerData.java:45) ~[?:?]
        at java.util.HashMap.compute(Unknown Source) ~[?:1.8.0_231]
        at de.md5lukas.waypoints.data.WPPlayerData.getPlayerData(WPPlayerData.java:41) ~[?:?]
        at de.md5lukas.waypoints.gui.WaypointProvider.<init>(WaypointProvider.java:187) ~[?:?]
        at de.md5lukas.waypoints.gui.GUIManager.openGUI(GUIManager.java:34) ~[?:?]
        at de.md5lukas.waypoints.command.WaypointsCommand.onCommand(WaypointsCommand.java:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-126]
        ... 17 more
>
```

plugins
![image](https://user-images.githubusercontent.com/34986564/75818509-465b7600-5d99-11ea-990d-eef152695345.png)

**Comment by Sytm** [comment]
Looking at the error message it seems like you somehow messed up the data storage of your player profile. (plugins/Md5Lukas-Commons/playerdata/[UUID].dat)

**Comment by thegamerx1** [comment]
sry for delay after deleting the playerdata folder its working
