### ISSUE TITLE
Some translations are missing messages (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by quarties** [Sytm/waypoints2#43]
**Describe the bug**
The plugin throws an error during enabling process.
```
[22:17:26] [Server thread/INFO]: [Waypoints] Enabling Waypoints v2.9.2
[22:17:26] [Server thread/ERROR]: Error occurred while enabling Waypoints v2.9.2 (Is it up to date?)
java.lang.IllegalArgumentException: Some translations are missing messages. Check the console for more details
	at de.md5lukas.commons.messages.MessageStore.<init>(MessageStore.java:58) ~[?:?]
	at de.md5lukas.waypoints.Waypoints.loadMessages(Waypoints.java:189) ~[?:?]
	at de.md5lukas.waypoints.Waypoints.onEnable(Waypoints.java:126) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-439]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-439]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-439]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-439]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-439]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-439]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-439]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-439]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-439]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:17:26] [Server thread/INFO]: [Waypoints] Disabling Waypoints v2.9.2
````

Also Md5-LukasCommon plugin throws an error about translations:
```
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] The following messages are missing: 
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] Language: de
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] chatAction.getId
command.scripting.help.title
command.scripting.help.clearWaypoint
command.scripting.help.selectWaypoint
command.scripting.clearWaypoint.wrongUsage
command.scripting.selectWaypoint.wrongUsage
inventory.waypoint.public.getId.displayName
inventory.waypoint.public.getId.description
inventory.waypoint.permission.getId.displayName
inventory.waypoint.permission.getId.description
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] Language: ru
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] chatAction.getId
command.scripting.help.title
command.scripting.help.clearWaypoint
command.scripting.help.selectWaypoint
command.scripting.clearWaypoint.wrongUsage
command.scripting.selectWaypoint.wrongUsage
inventory.waypoint.public.getId.displayName
inventory.waypoint.public.getId.description
inventory.waypoint.permission.getId.displayName
inventory.waypoint.permission.getId.description
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] Language: en
[22:17:26] [Server thread/ERROR]: [Md5Lukas-Commons] chatAction.getId
command.scripting.help.title
command.scripting.help.clearWaypoint
command.scripting.help.selectWaypoint
command.scripting.clearWaypoint.wrongUsage
command.scripting.selectWaypoint.wrongUsage
inventory.waypoint.public.getId.displayName
inventory.waypoint.public.getId.description
inventory.waypoint.permission.getId.displayName
inventory.waypoint.permission.getId.description
```

**To Reproduce**
1. Have PaperMC [#439](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/439/downloads/paper-1.16.5-439.jar) release installed.
2. Install Md5Lukas-Commons 1.2-b10
3. Install Waypoints 2.9.2
4. Try to run the server

**Expected behavior**
The plugin is enabled during the startup

**Server environment:**
 - OS: macOS Catalina 10.15.7 (19H114)
 - Java Version: 11 (I don't know the exact version, but I think I can ask my hosting provider if needed)
 - PaperMC [#439](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/439/downloads/paper-1.16.5-439.jar)
 - Md5Lukas-Commons 1.2-b10
 - Waypoints 2.9.2

**Comment by Sytm** [comment]
Yeah, the problem is that I have added entries to the translation file, and because comments and stuff I cannot automatically updated it without removing said comments, so you need to add these new entries either by yourself or if you have not changed them you can just delete `plugins/Waypoints/lang` directory

**Comment by quarties** [comment]
Thanks a lot!
