### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by DLmass** [Sytm/waypoints2#67]
Console errors on 1.19.

`[14:14:00] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Waypoints v3.4.1
java.lang.IllegalArgumentException: Could not find packet for type SPAWN_ENTITY_LIVING
	at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:98) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:113) ~[ProtocolLib.jar:?]
	at de.md5lukas.waypoints.util.Hologram.<init>(HologramManager.kt:100) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.util.HologramManager.createHologram(HologramManager.kt:27) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.variants.HologramPointer.update$lambda-1(HologramPointer.kt:30) ~[waypoints-3.4.1.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at de.md5lukas.waypoints.pointer.variants.HologramPointer.update(HologramPointer.kt:28) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.Pointer.show(Pointer.kt:14) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.PointerManagerImpl.show(PointerManagerImpl.kt:143) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.PointerManagerImpl.enable(PointerManagerImpl.kt:108) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.gui.pages.WaypointPage$updatePage$6.invoke(WaypointPage.kt:185) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.gui.pages.WaypointPage$updatePage$6.invoke(WaypointPage.kt:182) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.kinvs.items.GUIItem.click(GUIItem.kt:16) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.kinvs.GUI.onClick(GUI.kt:31) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.kinvs.GUIManager.onInventoryClick(GUIManager.kt:75) ~[waypoints-3.4.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3047) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-8]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:14:01] [Server thread/WARN]: [Waypoints] Task #16 for Waypoints v3.4.1 generated an exception
java.lang.IllegalArgumentException: Could not find packet for type SPAWN_ENTITY_LIVING
	at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:98) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:113) ~[ProtocolLib.jar:?]
	at de.md5lukas.waypoints.util.Hologram.<init>(HologramManager.kt:100) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.util.HologramManager.createHologram(HologramManager.kt:27) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.variants.HologramPointer.update$lambda-1(HologramPointer.kt:30) ~[waypoints-3.4.1.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at de.md5lukas.waypoints.pointer.variants.HologramPointer.update(HologramPointer.kt:28) ~[waypoints-3.4.1.jar:?]
	at de.md5lukas.waypoints.pointer.PointerTask.run(PointerTask.kt:12) ~[waypoints-3.4.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-8]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-8]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Sytm** [comment]
The problem is that ProtocolLib does not support Minecraft 1.19.

Once it officially supports it and the error message still appears I will look at it again.
