### ISSUE TITLE
Can't use 80% of the GUI

### ISSUE THREAD

**Issue by zLeqitEclipse** [Sytm/waypoints2#76]
When i press something in the GUI (for example: create waypoint, rename one and lots more) this error appears in the Server console.
`[16:44:53] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Waypoints v3.5.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2868) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
        at de.md5lukas.waypoints.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:98) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:91) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:176) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI.<init>(AnvilGUI.java:164) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[?:?]
        at de.md5lukas.waypoints.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[?:?]
        at de.md5lukas.waypoints.gui.WaypointsGUI.openCreateWaypoint(WaypointsGUI.kt:170) ~[?:?]
        at de.md5lukas.waypoints.gui.WaypointsGUI.openCreateWaypoint$default(WaypointsGUI.kt:116) ~[?:?]
        at de.md5lukas.waypoints.gui.pages.GUIFolderPage$updateControls$9.invoke(GUIFolderPage.kt:215) ~[?:?]
        at de.md5lukas.waypoints.gui.pages.GUIFolderPage$updateControls$9.invoke(GUIFolderPage.kt:184) ~[?:?]
        at de.md5lukas.waypoints.kinvs.items.GUIItem.click(GUIItem.kt:28) ~[?:?]
        at de.md5lukas.waypoints.kinvs.GUI.onClick$kinvs(GUI.kt:60) ~[?:?]
        at de.md5lukas.waypoints.kinvs.GUIManager.onInventoryClick(GUIManager.kt:75) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more`

Im using the latest Spigot 1.19.2 Release and latest ProtocolLib Dev Build. (if thats wrong please let me know)

EDIT: Even more worse, you can open the GUI and just take out the Items of there.

**Comment by DragaoNimhe** [comment]
Any update to this now that ProtocolLib has builds out for 1.19 (development)?
This is pretty much rendering the plugin completely unusable for our server.

**Comment by Frozenbloo** [comment]
This problem is also stopping my server from updating from 1.18 to 1.19. Its the only plugin that still hasn't been updated yet. I am considering dropping it but the players love it so much they would be distraught if it wasn't part of the 1.19 update.
