### ISSUE TITLE
Error spam in console when a waypoint is selected

### ISSUE THREAD

**Issue by raffel080108** [Sytm/waypoints2#79]
```
18.11 17:49:49 [Server] [WARN] [Waypoints] Task #144363 for Waypoints v3.5.4 generated an exception
18.11 17:49:49 [Server] [INFO] java.lang.IllegalArgumentException: Could not find packet for type SPAWN_ENTITY_LIVING
18.11 17:49:49 [Server] [INFO] at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
18.11 17:49:49 [Server] [INFO] at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
18.11 17:49:49 [Server] [INFO] at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:376) ~[ProtocolLib.jar:?]
18.11 17:49:49 [Server] [INFO] at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95) ~[ProtocolLib.jar:?]
18.11 17:49:49 [Server] [INFO] at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
18.11 17:49:49 [Server] [INFO] at de.md5lukas.waypoints.util.Hologram.<init>(HologramManager.kt:100) ~[waypoints-3.5.4.jar:?]
18.11 17:49:49 [Server] [INFO] at de.md5lukas.waypoints.util.HologramManager.createHologram(HologramManager.kt:27) ~[waypoints-3.5.4.jar:?]
18.11 17:49:49 [Server] [INFO] at de.md5lukas.waypoints.pointer.variants.HologramPointer.update$lambda-1(HologramPointer.kt:39) ~[waypoints-3.5.4.jar:?]
18.11 17:49:49 [Server] [INFO] at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
18.11 17:49:49 [Server] [INFO] at de.md5lukas.waypoints.pointer.variants.HologramPointer.update(HologramPointer.kt:38) ~[waypoints-3.5.4.jar:?]
18.11 17:49:49 [Server] [INFO] at de.md5lukas.waypoints.pointer.PointerTask.run(PointerTask.kt:12) ~[waypoints-3.5.4.jar:?]
18.11 17:49:49 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:49 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:49 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:49 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:49 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:49 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1845]
18.11 17:49:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
```
This error stacktrace gets spammed on console whenever someone has a waypoint selected

**Comment by Sytm** [comment]
This looks like a ProtocolLib issue, because it does not support Minecraft 1.19 yet. As a workaround you can disable the hologram pointer. For that set [this value](https://github.com/Sytm/waypoints/blob/7e332c2049e20c397b374b9b2f97b13bd4be5d07/waypoints/src/main/resources/config.yml#L230) to false
