### ISSUE TITLE
Not working with ProtocolLib 5

### ISSUE THREAD

**Issue by red-gecko27** [Sytm/waypoints2#84]
ProtocolLib Version:
``` 
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
build #610
```

Error:
```
[Waypoints] An issue occurred trying to create a hologram using ProtocolLib. Automatically disabling Holograms until the next restart.
java.lang.IllegalArgumentException: Could not find packet for type SPAWN_ENTITY_LIVING
at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:376) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:376) ~[?:?]
at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:111) ~[?:?]
at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[?:?]
at de.md5lukas.waypoints.util.Hologram.<init>(HologramManager.kt:100) ~[?:?]
at de.md5lukas.waypoints.util.HologramManager.createHologram(HologramManager.kt:27) ~[?:?]
at de.md5lukas.waypoints.pointer.variants.HologramPointer$update$1.invoke(HologramPointer.kt:45) ~[?:?]
at de.md5lukas.waypoints.pointer.variants.HologramPointer$update$1.invoke(HologramPointer.kt:44) ~[?:?]
at de.md5lukas.waypoints.pointer.variants.HologramPointer.update$lambda$1(HologramPointer.kt:44) ~[?:?]
at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
at de.md5lukas.waypoints.pointer.variants.HologramPointer.update(HologramPointer.kt:44) ~[?:?]
at de.md5lukas.waypoints.pointer.Pointer.show(Pointer.kt:14) ~[?:?]
at de.md5lukas.waypoints.pointer.PointerManagerImpl.show(PointerManagerImpl.kt:168) ~[?:?]
at de.md5lukas.waypoints.pointer.PointerManagerImpl.enable(PointerManagerImpl.kt:131) ~[?:?]
at de.md5lukas.waypoints.gui.pages.WaypointPage$updatePage$6.invoke(WaypointPage.kt:189) ~[?:?]
at de.md5lukas.waypoints.gui.pages.WaypointPage$updatePage$6.invoke(WaypointPage.kt:186) ~[?:?]
at de.md5lukas.waypoints.kinvs.items.GUIItem.click(GUIItem.kt:28) ~[?:?]
at de.md5lukas.waypoints.kinvs.GUI.onClick$kinvs(GUI.kt:60) ~[?:?]
at de.md5lukas.waypoints.kinvs.GUIManager.onInventoryClick(GUIManager.kt:75) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2757) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1133) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3637-Spigot-d90018e-4768df7]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NyaomiDEV** [comment]
https://github.com/dmulloy2/ProtocolLib/pull/1601

Since the update to 1.19 was merged, exactly. It will still work with <= 1.18.x; but yeah this is a bummer...

**Comment by Sytm** [comment]
I definitely haven't spent 3 hours trying to understand the Protocol changes and what went wrong :).

But thanks @NyaomiDEV for linking the PR on ProtocolLib, there was useful information in there!

**Comment by NyaomiDEV** [comment]
erm... @Sytm can we have a release, pretty please?

**Comment by Sytm** [comment]
Created a release.

I guess I didn't realize it's such a desired feature, sorry
